// Integration tests: validate HOSxP-simulated webhook fixture data against LRMS processing pipeline
// Reads real fixture files generated by hosxp-simulator from tests/fixtures/hosxp-simulated/
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { createHash } from 'crypto';
import { v4 as uuidv4 } from 'uuid';
import * as fs from 'fs';
import * as path from 'path';
import { createTestDb } from '../helpers/testDb';
import type { DatabaseAdapter } from '@/db/adapter';
import { SeedOrchestrator } from '@/db/seeds/index';
import { generateKey } from '@/lib/encryption';
import type { SseManager } from '@/lib/sse';
import {
  createApiKey,
  processWebhookPayload,
  processAncWebhook,
  processReferralCreate,
  processReferralUpdate,
  type WebhookPayload,
  type WebhookAncPayload,
  type WebhookReferralCreatePayload,
  type WebhookReferralUpdatePayload,
} from '@/services/webhook';

// ─── Fixture loading helpers ───

const FIXTURES_DIR = path.resolve(__dirname, '../fixtures/hosxp-simulated');

function loadFixture<T>(filename: string): T {
  const filePath = path.join(FIXTURES_DIR, filename);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Fixture file not found: ${filename}. Run hosxp-simulator (Task #1/#4) first.`);
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf-8')) as T;
}

function fixtureExists(filename: string): boolean {
  return fs.existsSync(path.join(FIXTURES_DIR, filename));
}

// ─── Test helpers ───

const TEST_ENCRYPTION_KEY = generateKey();
process.env.ENCRYPTION_KEY = TEST_ENCRYPTION_KEY;

class MockSseManager {
  public events: Array<{ event: string; data: unknown }> = [];

  broadcast(event: string, data: unknown): void {
    this.events.push({ event, data });
  }

  clearEvents(): void {
    this.events = [];
  }

  getEventsByType(type: string): Array<{ event: string; data: unknown }> {
    return this.events.filter(
      (e) => e.event === type || (e.data as Record<string, unknown>)?.type === type,
    );
  }
}

function asSse(mock: MockSseManager): SseManager {
  return mock as unknown as SseManager;
}

function cidHash(cid: string): string {
  return createHash('sha256').update(cid).digest('hex');
}

// ─── Suite 1: Data Shape Validation (no DB required) ───

describe('Suite 1: Fixture Data Shape Validation', () => {
  it('fixture files exist in tests/fixtures/hosxp-simulated/', () => {
    const requiredFiles = ['anc-patients.json', 'labor-patients.json', 'referral-create.json'];
    for (const file of requiredFiles) {
      expect(fixtureExists(file), `Missing fixture: ${file} — run hosxp-simulator first`).toBe(
        true,
      );
    }
  });

  describe('ANC fixture shape', () => {
    it('has required top-level fields', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      expect(payload.type).toBe('anc_data');
      expect(typeof payload.hospitalCode).toBe('string');
      expect(payload.hospitalCode.length).toBeGreaterThan(0);
      expect(Array.isArray(payload.patients)).toBe(true);
      expect(payload.patients.length).toBeGreaterThan(0);
    });

    it('every ANC patient has required fields with correct types', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      for (const [i, p] of payload.patients.entries()) {
        // hn is null for community ANC patients not registered in hospital patient table (real HOSxP data)
        expect(
          p.hn === null || typeof p.hn === 'string',
          `patients[${i}].hn must be null or string`,
        ).toBe(true);
        expect(typeof p.name, `patients[${i}].name`).toBe('string');
        expect(p.name.length, `patients[${i}].name non-empty`).toBeGreaterThan(0);
        expect(typeof p.cid, `patients[${i}].cid`).toBe('string');
        expect(p.cid.length, `patients[${i}].cid is 13 digits`).toBe(13);
        expect(typeof p.birthday, `patients[${i}].birthday`).toBe('string');
        expect(typeof p.pregNo, `patients[${i}].pregNo`).toBe('number');
        expect(p.pregNo, `patients[${i}].pregNo >= 1`).toBeGreaterThanOrEqual(1);
      }
    });

    it('all ANC patients have null hn (HOSxP registers ANC via community person registry, not hospital patient table)', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      // This validates the real-world finding: person_anc rows don't have patient_hn set
      const nullHnCount = payload.patients.filter((p) => p.hn === null).length;
      expect(nullHnCount).toBe(payload.patients.length);
    });

    it('CID is exactly 13 digits for all ANC patients', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      for (const [i, p] of payload.patients.entries()) {
        expect(
          /^\d{13}$/.test(p.cid),
          `patients[${i}].cid "${p.cid}" must be exactly 13 digits`,
        ).toBe(true);
      }
    });

    it('all CIDs are unique within the ANC payload', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      const cids = payload.patients.map((p) => p.cid);
      const unique = new Set(cids);
      expect(unique.size).toBe(cids.length);
    });

    it('birthday is YYYY-MM-DD format', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      for (const [i, p] of payload.patients.entries()) {
        expect(
          /^\d{4}-\d{2}-\d{2}$/.test(p.birthday),
          `patients[${i}].birthday "${p.birthday}" must be YYYY-MM-DD`,
        ).toBe(true);
      }
    });

    it('riskLevel is one of the valid 4-tier values when present', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      const validLevels = ['LOW', 'HR1', 'HR2', 'HR3'];
      for (const [i, p] of payload.patients.entries()) {
        if (p.riskLevel != null) {
          expect(validLevels, `patients[${i}].riskLevel "${p.riskLevel}"`).toContain(p.riskLevel);
        }
      }
    });

    it('location codes are 2-character strings when present', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      for (const [i, p] of payload.patients.entries()) {
        if (p.changwatCode != null) {
          expect(
            p.changwatCode.length,
            `patients[${i}].changwatCode "${p.changwatCode}" max 2 chars`,
          ).toBeLessThanOrEqual(2);
        }
        if (p.amphurCode != null) {
          expect(
            p.amphurCode.length,
            `patients[${i}].amphurCode "${p.amphurCode}" max 2 chars`,
          ).toBeLessThanOrEqual(2);
        }
        if (p.tambonCode != null) {
          expect(
            p.tambonCode.length,
            `patients[${i}].tambonCode "${p.tambonCode}" max 2 chars`,
          ).toBeLessThanOrEqual(2);
        }
      }
    });

    it('lmp/edc dates are YYYY-MM-DD when provided', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      const dateRe = /^\d{4}-\d{2}-\d{2}$/;
      for (const [i, p] of payload.patients.entries()) {
        if (p.lmp != null) {
          expect(dateRe.test(p.lmp), `patients[${i}].lmp "${p.lmp}"`).toBe(true);
        }
        if (p.edc != null) {
          expect(dateRe.test(p.edc), `patients[${i}].edc "${p.edc}"`).toBe(true);
        }
      }
    });

    it('ANC visits have required fields when present', () => {
      const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
      for (const [i, p] of payload.patients.entries()) {
        if (!p.visits) continue;
        for (const [j, v] of p.visits.entries()) {
          expect(typeof v.date, `patients[${i}].visits[${j}].date`).toBe('string');
          expect(typeof v.visitNumber, `patients[${i}].visits[${j}].visitNumber`).toBe('number');
        }
      }
    });
  });

  describe('Labor fixture shape', () => {
    it('has required top-level fields', () => {
      const payload = loadFixture<WebhookPayload>('labor-patients.json');
      expect(typeof payload.hospitalCode).toBe('string');
      expect(payload.hospitalCode.length).toBeGreaterThan(0);
      expect(Array.isArray(payload.patients)).toBe(true);
      expect(payload.patients.length).toBeGreaterThan(0);
    });

    it('every labor patient has required fields', () => {
      const payload = loadFixture<WebhookPayload>('labor-patients.json');
      for (const [i, p] of payload.patients.entries()) {
        expect(typeof p.hn, `patients[${i}].hn`).toBe('string');
        expect(typeof p.an, `patients[${i}].an`).toBe('string');
        expect(typeof p.name, `patients[${i}].name`).toBe('string');
        expect(typeof p.cid, `patients[${i}].cid`).toBe('string');
        expect(p.cid.length, `patients[${i}].cid is 13 digits`).toBe(13);
        expect(typeof p.age, `patients[${i}].age`).toBe('number');
        expect(typeof p.admit_date, `patients[${i}].admit_date`).toBe('string');
      }
    });

    it('admit_date is ISO 8601 format', () => {
      const payload = loadFixture<WebhookPayload>('labor-patients.json');
      for (const [i, p] of payload.patients.entries()) {
        const d = new Date(p.admit_date);
        expect(
          isNaN(d.getTime()),
          `patients[${i}].admit_date "${p.admit_date}" must be parseable ISO 8601`,
        ).toBe(false);
      }
    });

    it('hospitalCode matches ANC fixture (same source hospital)', () => {
      const labor = loadFixture<WebhookPayload>('labor-patients.json');
      const anc = loadFixture<WebhookAncPayload>('anc-patients.json');
      expect(labor.hospitalCode).toBe(anc.hospitalCode);
    });

    it('mode is valid when present', () => {
      const payload = loadFixture<WebhookPayload>('labor-patients.json');
      if (payload.mode != null) {
        expect(['incremental', 'full_snapshot']).toContain(payload.mode);
      }
    });

    it('labor_status values are valid when present', () => {
      const payload = loadFixture<WebhookPayload>('labor-patients.json');
      for (const [i, p] of payload.patients.entries()) {
        if (p.labor_status != null) {
          expect(
            ['ACTIVE', 'DELIVERED'],
            `patients[${i}].labor_status "${p.labor_status}"`,
          ).toContain(p.labor_status);
        }
      }
    });
  });

  describe('Referral create fixture shape', () => {
    it('has required fields for type referral', () => {
      const payload = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
      expect(payload.type).toBe('referral');
      expect(typeof payload.hospitalCode).toBe('string');
      expect(typeof payload.referralId).toBe('string');
      expect(payload.referralId.length).toBeGreaterThan(0);
      expect(typeof payload.hn).toBe('string');
      expect(typeof payload.cid).toBe('string');
      expect(payload.cid.length).toBe(13);
      expect(typeof payload.name).toBe('string');
      expect(typeof payload.toHospitalCode).toBe('string');
      expect(typeof payload.reason).toBe('string');
    });

    it('CID is exactly 13 digits', () => {
      const payload = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
      expect(/^\d{13}$/.test(payload.cid)).toBe(true);
    });

    it('urgencyLevel is valid when present', () => {
      const payload = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
      if (payload.urgencyLevel != null) {
        expect(['ROUTINE', 'URGENT', 'EMERGENCY']).toContain(payload.urgencyLevel);
      }
    });

    it('referralId is zero-padded integer format (not slash format)', () => {
      const payload = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
      // Real HOSxP data: referout_number is an integer zero-padded to 8 chars e.g. "00000014"
      // NOT slash format "3803/68" as documented in old spec
      expect(/^\d+$/.test(payload.referralId)).toBe(true);
      expect(payload.referralId).toBe('00000014');
    });

    it('real fixture has expected hospitals and diagnosis', () => {
      const payload = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
      expect(payload.hospitalCode).toBe('10679');
      expect(payload.toHospitalCode).toBe('11304');
      expect(payload.diagnosisCode).toBe('S330');
      expect(payload.urgencyLevel).toBe('ROUTINE'); // mapped from null emergency_type_id
    });
  });

  describe('Referral update fixture shape', () => {
    it('has required fields for type referral_update', () => {
      if (!fixtureExists('referral-update.json')) return;
      const payload = loadFixture<WebhookReferralUpdatePayload>('referral-update.json');
      expect(payload.type).toBe('referral_update');
      expect(typeof payload.hospitalCode).toBe('string');
      expect(typeof payload.referralId).toBe('string');
      expect(typeof payload.fromHospitalCode).toBe('string');
      expect(typeof payload.status).toBe('string');
    });

    it('status is a valid referral status', () => {
      if (!fixtureExists('referral-update.json')) return;
      const payload = loadFixture<WebhookReferralUpdatePayload>('referral-update.json');
      expect(['ACCEPTED', 'IN_TRANSIT', 'ARRIVED', 'REJECTED']).toContain(payload.status);
    });

    it('referralId matches the create fixture', () => {
      if (!fixtureExists('referral-update.json')) return;
      const create = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
      const update = loadFixture<WebhookReferralUpdatePayload>('referral-update.json');
      expect(update.referralId).toBe(create.referralId);
    });

    it('fromHospitalCode matches the create fixture hospitalCode', () => {
      if (!fixtureExists('referral-update.json')) return;
      const create = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
      const update = loadFixture<WebhookReferralUpdatePayload>('referral-update.json');
      expect(update.fromHospitalCode).toBe(create.hospitalCode);
    });

    it('referral update reason contains Thai text', () => {
      if (!fixtureExists('referral-update.json')) return;
      const update = loadFixture<WebhookReferralUpdatePayload>('referral-update.json');
      // Real data has Thai reason: "รับส่งต่อ — เตียงแผนกสูติกรรมว่าง"
      expect(update.reason).toBeDefined();
      expect(update.reason!.length).toBeGreaterThan(0);
    });
  });
});

// Helper: get existing hospital id from seeded data by hcode, or insert if missing
async function getOrCreateHospital(
  db: DatabaseAdapter,
  hcode: string,
  name: string,
  level: string,
): Promise<string> {
  const rows = await db.query<{ id: string }>('SELECT id FROM hospitals WHERE hcode = ?', [hcode]);
  if (rows.length > 0) return rows[0].id;
  const id = uuidv4();
  const now = new Date().toISOString();
  await db.execute(
    `INSERT INTO hospitals (id, hcode, name, level, is_active, connection_status, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
    [id, hcode, name, level, true, 'UNKNOWN', now, now],
  );
  return id;
}

// ─── Suite 2: ANC Processing Validation ───

describe('Suite 2: ANC Processing Validation', () => {
  let db: DatabaseAdapter;
  let sseManager: MockSseManager;
  let hospitalId: string;

  beforeEach(async () => {
    db = await createTestDb();
    await new SeedOrchestrator().run(db);
    sseManager = new MockSseManager();

    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    hospitalId = await getOrCreateHospital(db, ancFixture.hospitalCode, 'รพ.ทดสอบ HOSxP', 'F1');
    await createApiKey(db, hospitalId, 'HOSxP Simulated Test Key');
  });

  afterEach(async () => {
    await db.close();
  });

  it('processes all ANC patients without errors (including null HN patients)', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    const result = await processAncWebhook(db, hospitalId, payload, asSse(sseManager));
    expect(result.patientsProcessed).toBe(payload.patients.length);
    expect(result.created).toBeGreaterThan(0);
    expect(result.deleted).toBe(0);
  });

  it('null HN patients use empty string in maternal_journeys (not null — NOT NULL constraint)', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    const rows = await db.query<{ hn: string | null }>(
      'SELECT hn FROM maternal_journeys WHERE hospital_id = ?',
      [hospitalId],
    );
    // All rows should exist and hn should be empty string (not null — DB column is NOT NULL)
    expect(rows.length).toBe(payload.patients.length);
    for (const row of rows) {
      expect(row.hn).not.toBeNull();
      expect(row.hn).toBe(''); // null HN from fixture → empty string in DB
    }
  });

  it('creates a maternal_journeys record for each ANC patient', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    const rows = await db.query<{ count: number }>(
      'SELECT COUNT(*) as count FROM maternal_journeys WHERE hospital_id = ?',
      [hospitalId],
    );
    expect(rows[0].count).toBe(payload.patients.length);
  });

  it('CID is never stored as plaintext — only hash and encrypted form', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    for (const [i, original] of payload.patients.entries()) {
      const expectedHash = cidHash(original.cid);
      const rows = await db.query<{ cid: string; cid_hash: string }>(
        'SELECT cid, cid_hash FROM maternal_journeys WHERE cid_hash = ?',
        [expectedHash],
      );
      expect(rows.length, `patients[${i}]: journey found by CID hash`).toBeGreaterThan(0);
      const journey = rows[0];
      // Plain CID must NOT appear in the stored cid field
      expect(journey.cid, `Journey ${i}: stored cid must not be the plain CID`).not.toBe(
        original.cid,
      );
      // CID hash must be correct SHA-256
      expect(journey.cid_hash).toBe(expectedHash);
    }
  });

  it('encrypted CID is base64-encoded AES-256-GCM ciphertext (not plain digits)', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    const journeys = await db.query<{ cid: string }>(
      'SELECT cid FROM maternal_journeys WHERE hospital_id = ?',
      [hospitalId],
    );

    for (const j of journeys) {
      // Encrypted value is base64 — cannot be all-digit 13-char string
      expect(/^\d{13}$/.test(j.cid)).toBe(false);
      // Should be valid base64 (longer than 13 chars due to IV + auth tag + ciphertext)
      expect(j.cid.length).toBeGreaterThan(13);
    }
  });

  it('name is encrypted (not stored as plain Thai text)', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    const journeys = await db.query<{ name: string }>(
      'SELECT name FROM maternal_journeys WHERE hospital_id = ?',
      [hospitalId],
    );

    for (const [i, original] of payload.patients.entries()) {
      expect(journeys[i].name).not.toBe(original.name);
      // Encrypted value should be longer than original (IV + auth tag overhead)
      expect(journeys[i].name.length).toBeGreaterThan(0);
    }
  });

  it('risk level is stored correctly for each patient', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    for (const p of payload.patients) {
      if (!p.riskLevel) continue;
      const expectedHash = cidHash(p.cid);
      const rows = await db.query<{ anc_risk_level: string }>(
        'SELECT anc_risk_level FROM maternal_journeys WHERE cid_hash = ?',
        [expectedHash],
      );
      expect(rows.length).toBeGreaterThan(0);
      expect(rows[0].anc_risk_level).toBe(p.riskLevel);
    }
  });

  it('location codes (changwat/amphur/tambon) are preserved', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    for (const p of payload.patients) {
      if (!p.changwatCode && !p.amphurCode && !p.tambonCode) continue;
      const expectedHash = cidHash(p.cid);
      const rows = await db.query<{
        changwat_code: string | null;
        amphur_code: string | null;
        tambon_code: string | null;
      }>(
        'SELECT changwat_code, amphur_code, tambon_code FROM maternal_journeys WHERE cid_hash = ?',
        [expectedHash],
      );
      expect(rows.length).toBeGreaterThan(0);
      if (p.changwatCode) expect(rows[0].changwat_code).toBe(p.changwatCode);
      if (p.amphurCode) expect(rows[0].amphur_code).toBe(p.amphurCode);
      if (p.tambonCode) expect(rows[0].tambon_code).toBe(p.tambonCode);
    }
  });

  it('ANC visits in fixture are persisted to cached_anc_visits table', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    const totalFixtureVisits = payload.patients.reduce(
      (sum, p) => sum + (p.visits?.length ?? 0),
      0,
    );
    expect(totalFixtureVisits).toBeGreaterThan(0); // Fixture has 26 total visits

    // processAncWebhook persists visit records to cached_anc_visits (replace strategy)
    const visitRows = await db.query<{ count: number }>(
      `SELECT COUNT(*) as count FROM cached_anc_visits
       WHERE journey_id IN (SELECT id FROM maternal_journeys WHERE hospital_id = ?)`,
      [hospitalId],
    );
    expect(visitRows[0].count).toBe(totalFixtureVisits);
  });

  it('fetalHr and fundalHeightCm are always null in fixture visits (HOSxP mapping gap)', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    for (const p of payload.patients) {
      for (const v of p.visits ?? []) {
        expect(v.fetalHr, 'fetalHr always null in real HOSxP data').toBeNull();
        expect(v.fundalHeightCm, 'fundalHeightCm always null in real HOSxP data').toBeNull();
      }
    }
  });

  it('only the last visit per patient has weight and BP data (from opdscreen join)', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    for (const [i, p] of payload.patients.entries()) {
      if (!p.visits || p.visits.length < 2) continue;
      const allButLast = p.visits.slice(0, -1);
      const last = p.visits[p.visits.length - 1];
      // Earlier visits have null vitals
      for (const v of allButLast) {
        expect(v.weightKg, `patients[${i}] non-last visit weightKg should be null`).toBeNull();
        expect(v.bpSystolic, `patients[${i}] non-last visit bpSystolic should be null`).toBeNull();
      }
      // Last visit has weight and BP
      expect(last.weightKg, `patients[${i}] last visit weightKg`).not.toBeNull();
      expect(last.bpSystolic, `patients[${i}] last visit bpSystolic`).not.toBeNull();
    }
  });

  it('exactly 1 of 5 ANC patients has location codes (changwat/amphur/tambon)', () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    const withLocation = payload.patients.filter(
      (p) => p.changwatCode != null || p.amphurCode != null || p.tambonCode != null,
    );
    expect(withLocation.length).toBe(1);
    // The one patient with location: CID 1869900365675, changwat=25, amphur=08, tambon=10
    expect(withLocation[0].changwatCode).toBe('25');
    expect(withLocation[0].amphurCode).toBe('08');
    expect(withLocation[0].tambonCode).toBe('10');
  });

  it('ANC fixture has exactly 5 patients with expected visit counts', () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    expect(payload.patients.length).toBe(5);
    const visitCounts = payload.patients.map((p) => p.visits?.length ?? 0);
    // Patient 0: 8 visits, Patient 1: 2 visits, Patient 2: 7 visits, Patient 3: 4 visits, Patient 4: 5 visits
    expect(visitCounts).toEqual([8, 2, 7, 4, 5]);
  });

  it('all patients have riskLevel LOW (person_anc_risk table is empty in this HOSxP instance)', () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    for (const [i, p] of payload.patients.entries()) {
      expect(p.riskLevel, `patients[${i}].riskLevel`).toBe('LOW');
    }
  });

  it('hospital connection_status is set to ONLINE after processing', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    const rows = await db.query<{ connection_status: string }>(
      'SELECT connection_status FROM hospitals WHERE id = ?',
      [hospitalId],
    );
    expect(rows[0].connection_status).toBe('ONLINE');
  });

  it('SSE events are broadcast for ANC processing', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    // Coalesced contract (2026-07-17): ONE bulk event per ingest call whose
    // counts cover every processed patient — not one event per patient.
    const journeyEvents = sseManager.getEventsByType('journey_update');
    expect(journeyEvents).toHaveLength(1);
    const evt = journeyEvents[0].data as Record<string, unknown>;
    expect(evt.bulk).toBe(true);
    expect(Number(evt.created) + Number(evt.updated)).toBe(payload.patients.length);
  });

  it('second call with same data updates rather than duplicates', async () => {
    const payload = loadFixture<WebhookAncPayload>('anc-patients.json');
    const result1 = await processAncWebhook(db, hospitalId, payload, asSse(sseManager));
    const result2 = await processAncWebhook(db, hospitalId, payload, asSse(sseManager));

    // Second call should update, not create new
    expect(result2.created).toBe(0);
    expect(result2.updated).toBe(result1.created);

    // Total journey count should not have doubled
    const rows = await db.query<{ count: number }>(
      'SELECT COUNT(*) as count FROM maternal_journeys WHERE hospital_id = ?',
      [hospitalId],
    );
    expect(rows[0].count).toBe(payload.patients.length);
  });
});

// ─── Suite 3: Labor Processing Validation ───

describe('Suite 3: Labor Processing Validation', () => {
  let db: DatabaseAdapter;
  let sseManager: MockSseManager;
  let hospitalId: string;

  beforeEach(async () => {
    db = await createTestDb();
    await new SeedOrchestrator().run(db);
    sseManager = new MockSseManager();

    const laborFixture = loadFixture<WebhookPayload>('labor-patients.json');
    hospitalId = await getOrCreateHospital(
      db,
      laborFixture.hospitalCode,
      'รพ.ทดสอบ HOSxP Labor',
      'F1',
    );
    await createApiKey(db, hospitalId, 'HOSxP Labor Test Key');
  });

  afterEach(async () => {
    await db.close();
  });

  it('processes all labor patients without errors', async () => {
    const payload = loadFixture<WebhookPayload>('labor-patients.json');
    const result = await processWebhookPayload(db, hospitalId, payload, asSse(sseManager));
    expect(result.patientsProcessed).toBe(payload.patients.length);
    expect(result.deleted).toBe(0);
  });

  it('creates cached_patients records for each labor patient', async () => {
    const payload = loadFixture<WebhookPayload>('labor-patients.json');
    await processWebhookPayload(db, hospitalId, payload, asSse(sseManager));

    const rows = await db.query<{ count: number }>(
      'SELECT COUNT(*) as count FROM cached_patients WHERE hospital_id = ?',
      [hospitalId],
    );
    expect(rows[0].count).toBe(payload.patients.length);
  });

  it('CID is hashed with SHA-256 for labor patients', async () => {
    const payload = loadFixture<WebhookPayload>('labor-patients.json');
    await processWebhookPayload(db, hospitalId, payload, asSse(sseManager));

    for (const p of payload.patients) {
      const expectedHash = cidHash(p.cid);
      const rows = await db.query<{ cid_hash: string }>(
        'SELECT cid_hash FROM cached_patients WHERE hospital_id = ? AND an = ?',
        [hospitalId, p.an],
      );
      expect(rows.length).toBeGreaterThan(0);
      expect(rows[0].cid_hash).toBe(expectedHash);
    }
  });

  it('labor fixture has exactly 1 active patient with expected values', () => {
    const payload = loadFixture<WebhookPayload>('labor-patients.json');
    expect(payload.patients.length).toBe(1);
    expect(payload.mode).toBe('incremental');
    const p = payload.patients[0];
    expect(p.hn).toBe('006800004');
    expect(p.an).toBe('690000004');
    expect(p.age).toBe(30);
    expect(p.gravida).toBe(1);
    expect(p.ga_weeks).toBe(40);
    expect(p.height_cm).toBe(168);
    expect(p.weight_kg).toBe(87.0);
    expect(p.labor_status).toBe('ACTIVE');
    expect(p.anc_count).toBeNull(); // known gap: admit records don't carry ANC count
    expect(p.admit_date).toBe('2026-03-25T15:02:13+07:00');
  });

  it('labor patients with null anc_count are handled gracefully', async () => {
    const payload = loadFixture<WebhookPayload>('labor-patients.json');
    const nullCountPatients = payload.patients.filter((p) => p.anc_count == null);
    // There should be at least one in the fixture
    expect(nullCountPatients.length).toBeGreaterThan(0);

    // Should not throw
    await expect(
      processWebhookPayload(db, hospitalId, payload, asSse(sseManager)),
    ).resolves.not.toThrow();
  });

  it('CPD score can be calculated from labor fixture data', async () => {
    const payload = loadFixture<WebhookPayload>('labor-patients.json');
    // Import here to avoid circular issues at module level
    const { calculateCpdScore } = await import('@/services/cpd-score');

    for (const p of payload.patients) {
      const factors = {
        gravida: p.gravida ?? undefined,
        gaWeeks: p.ga_weeks ?? undefined,
        ancCount: p.anc_count ?? undefined,
        heightCm: p.height_cm ?? undefined,
        weightDiffKg: p.weight_diff_kg ?? undefined,
        fundalHeightCm: p.fundal_height_cm ?? undefined,
        usWeightG: p.us_weight_g ?? undefined,
        hematocritPct: p.hematocrit_pct ?? undefined,
      };
      // Should not throw even with partial data
      expect(() => calculateCpdScore(factors)).not.toThrow();
      const result = calculateCpdScore(factors);
      expect(typeof result.score).toBe('number');
      expect(['LOW', 'MEDIUM', 'HIGH']).toContain(result.riskLevel);
    }
  });

  it('hospital connection_status is set to ONLINE after labor processing', async () => {
    const payload = loadFixture<WebhookPayload>('labor-patients.json');
    await processWebhookPayload(db, hospitalId, payload, asSse(sseManager));

    const rows = await db.query<{ connection_status: string }>(
      'SELECT connection_status FROM hospitals WHERE id = ?',
      [hospitalId],
    );
    expect(rows[0].connection_status).toBe('ONLINE');
  });

  it('SSE sync-complete event is broadcast', async () => {
    const payload = loadFixture<WebhookPayload>('labor-patients.json');
    await processWebhookPayload(db, hospitalId, payload, asSse(sseManager));

    const syncEvents = sseManager.getEventsByType('sync-complete');
    expect(syncEvents.length).toBeGreaterThan(0);
  });
});

// ─── Suite 4: Referral Processing Validation ───

describe('Suite 4: Referral Processing Validation', () => {
  let db: DatabaseAdapter;
  let sseManager: MockSseManager;
  let fromHospitalId: string;
  let toHospitalId: string;

  beforeEach(async () => {
    db = await createTestDb();
    await new SeedOrchestrator().run(db);
    sseManager = new MockSseManager();

    const createFixture = loadFixture<WebhookReferralCreatePayload>('referral-create.json');

    fromHospitalId = await getOrCreateHospital(
      db,
      createFixture.hospitalCode,
      'รพ.ต้นทาง ทดสอบ',
      'F1',
    );
    await createApiKey(db, fromHospitalId, 'From Hospital Key');

    toHospitalId = await getOrCreateHospital(
      db,
      createFixture.toHospitalCode,
      'รพ.ปลายทาง ทดสอบ',
      'A_S',
    );
    await createApiKey(db, toHospitalId, 'To Hospital Key');
  });

  afterEach(async () => {
    await db.close();
  });

  it('creates a referral record with status INITIATED', async () => {
    const payload = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
    const result = await processReferralCreate(db, fromHospitalId, payload, asSse(sseManager));

    expect(result.referralId).toBe(payload.referralId);
    expect(result.status).toBe('INITIATED');

    const rows = await db.query<{ status: string; refer_number: string }>(
      'SELECT status, refer_number FROM cached_referrals WHERE from_hospital_id = ? AND refer_number = ?',
      [fromHospitalId, payload.referralId],
    );
    expect(rows.length).toBe(1);
    expect(rows[0].status).toBe('INITIATED');
    expect(rows[0].refer_number).toBe(payload.referralId);
  });

  it('compound key (hospitalCode + referralId) prevents duplicate on re-send', async () => {
    const payload = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
    await processReferralCreate(db, fromHospitalId, payload, asSse(sseManager));
    await processReferralCreate(db, fromHospitalId, payload, asSse(sseManager));

    const rows = await db.query<{ count: number }>(
      'SELECT COUNT(*) as count FROM cached_referrals WHERE from_hospital_id = ? AND refer_number = ?',
      [fromHospitalId, payload.referralId],
    );
    expect(rows[0].count).toBe(1);
  });

  it('referral update changes status correctly', async () => {
    if (!fixtureExists('referral-update.json')) return;

    const createPayload = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
    const updatePayload = loadFixture<WebhookReferralUpdatePayload>('referral-update.json');

    // Create referral first
    await processReferralCreate(db, fromHospitalId, createPayload, asSse(sseManager));

    // Now update — sent from the receiving hospital
    const result = await processReferralUpdate(db, toHospitalId, updatePayload, asSse(sseManager));
    expect(result.referralId).toBe(updatePayload.referralId);
    expect(result.status).toBe(updatePayload.status);

    const rows = await db.query<{ status: string }>(
      'SELECT status FROM cached_referrals WHERE from_hospital_id = ? AND refer_number = ?',
      [fromHospitalId, updatePayload.referralId],
    );
    expect(rows.length).toBe(1);
    expect(rows[0].status).toBe(updatePayload.status);
  });

  it('SSE referral_update event is broadcast on create', async () => {
    const payload = loadFixture<WebhookReferralCreatePayload>('referral-create.json');
    await processReferralCreate(db, fromHospitalId, payload, asSse(sseManager));

    const events = sseManager.getEventsByType('referral_update');
    expect(events.length).toBeGreaterThan(0);
  });

  it('cross-hospital CID matching works: patient from ANC matches in referral', async () => {
    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    const referralFixture = loadFixture<WebhookReferralCreatePayload>('referral-create.json');

    // First insert ANC data
    await processAncWebhook(db, fromHospitalId, ancFixture, asSse(sseManager));

    // Now create referral — same CID should link to existing journey
    await processReferralCreate(db, fromHospitalId, referralFixture, asSse(sseManager));

    const cidHashValue = cidHash(referralFixture.cid);
    const rows = await db.query<{ journey_id: string | null }>(
      `SELECT journey_id FROM cached_referrals WHERE from_hospital_id = ? AND refer_number = ?`,
      [fromHospitalId, referralFixture.referralId],
    );
    expect(rows.length).toBe(1);
    // journey_id should be linked (not null) because ANC data was there first
    expect(rows[0].journey_id).not.toBeNull();

    // Verify it maps to the correct journey via CID hash
    const journeyRows = await db.query<{ id: string }>(
      'SELECT id FROM maternal_journeys WHERE cid_hash = ?',
      [cidHashValue],
    );
    expect(journeyRows.length).toBeGreaterThan(0);
    expect(rows[0].journey_id).toBe(journeyRows[0].id);
  });
});

// ─── Suite 5: Referral Check API Logic Validation ───

describe('Suite 5: Referral Check API Logic Validation', () => {
  let db: DatabaseAdapter;
  let sseManager: MockSseManager;
  let hospitalId: string;

  beforeEach(async () => {
    db = await createTestDb();
    await new SeedOrchestrator().run(db);
    sseManager = new MockSseManager();

    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    hospitalId = await getOrCreateHospital(db, ancFixture.hospitalCode, 'รพ.ทดสอบ Check', 'F1');
    await createApiKey(db, hospitalId, 'Check Test Key');
    // Seed ANC data
    await processAncWebhook(db, hospitalId, ancFixture, asSse(sseManager));
  });

  afterEach(async () => {
    await db.close();
  });

  it('referral-check fixture has 3 CIDs including known ANC patient and unknown CID', () => {
    const checkFixture = loadFixture<Array<{ cid: string }>>('referral-check.json');
    expect(checkFixture.length).toBe(3);
    // First is ANC patient, second is labor patient, third is unknown
    expect(checkFixture[0].cid).toBe('1770401294201'); // ANC patient 0
    expect(checkFixture[1].cid).toBe('0999991049501'); // Labor patient
    expect(checkFixture[2].cid).toBe('0000000000000'); // Unknown
  });

  it('patient with ANC data: CID hash lookup finds the journey', async () => {
    const checkFixture = loadFixture<Array<{ cid: string }>>('referral-check.json');
    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');

    // The first check CID in the fixture should be one of the ANC patients
    const knownCids = ancFixture.patients.map((p) => p.cid);
    const knownCheckCid = checkFixture.find((c) => knownCids.includes(c.cid));
    if (!knownCheckCid) return; // Skip if fixture doesn't overlap

    const hashValue = cidHash(knownCheckCid.cid);
    const rows = await db.query<{ care_stage: string }>(
      'SELECT care_stage FROM maternal_journeys WHERE cid_hash = ?',
      [hashValue],
    );
    expect(rows.length).toBeGreaterThan(0);
    expect(rows[0].care_stage).toBe('PREGNANCY');
  });

  it('unknown CID "0000000000000" returns no journey', async () => {
    const hashValue = cidHash('0000000000000');
    const rows = await db.query<{ id: string }>(
      'SELECT id FROM maternal_journeys WHERE cid_hash = ?',
      [hashValue],
    );
    expect(rows.length).toBe(0);
  });

  it('unknown CID (not in ANC or labor) returns no journey', async () => {
    const checkFixture = loadFixture<Array<{ cid: string }>>('referral-check.json');
    const ancCids = loadFixture<WebhookAncPayload>('anc-patients.json').patients.map((p) => p.cid);
    const laborCids = loadFixture<WebhookPayload>('labor-patients.json').patients.map((p) => p.cid);
    const knownCids = new Set([...ancCids, ...laborCids]);

    const unknownCheck = checkFixture.find((c) => !knownCids.has(c.cid));
    if (!unknownCheck) return; // All fixture CIDs are known

    const hashValue = cidHash(unknownCheck.cid);
    const rows = await db.query<{ id: string }>(
      'SELECT id FROM maternal_journeys WHERE cid_hash = ?',
      [hashValue],
    );
    expect(rows.length).toBe(0);
  });

  it('referral check fixture CIDs are 13 digits', () => {
    const checkFixture = loadFixture<Array<{ cid: string }>>('referral-check.json');
    for (const [i, entry] of checkFixture.entries()) {
      expect(
        /^\d{13}$/.test(entry.cid),
        `referral-check[${i}].cid "${entry.cid}" must be 13 digits`,
      ).toBe(true);
    }
  });
});

// ─── Suite 6: Edge Case Validation ───

describe('Suite 6: Edge Case Validation from Real Fixture Data', () => {
  let db: DatabaseAdapter;
  let sseManager: MockSseManager;
  let hospitalId: string;

  beforeEach(async () => {
    db = await createTestDb();
    await new SeedOrchestrator().run(db);
    sseManager = new MockSseManager();

    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    hospitalId = await getOrCreateHospital(
      db,
      ancFixture.hospitalCode,
      'รพ.ทดสอบ Edge Cases',
      'F1',
    );
    await createApiKey(db, hospitalId, 'Edge Case Test Key');
  });

  afterEach(async () => {
    await db.close();
  });

  it('ANC patients with lmp and edc present are processed without errors', async () => {
    // Real fixture: all 5 patients have lmp and edc set (community ANC has complete dates)
    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    const withDates = ancFixture.patients.filter((p) => p.lmp != null && p.edc != null);
    expect(withDates.length).toBe(ancFixture.patients.length); // All have dates in real data

    await expect(
      processAncWebhook(db, hospitalId, ancFixture, asSse(sseManager)),
    ).resolves.not.toThrow();
  });

  it('patients with null visit fields (bp, fetalHr) are processed without errors', async () => {
    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    const nullVisitFieldPatients = ancFixture.patients.filter((p) =>
      p.visits?.some((v) => v.bpSystolic == null || v.bpDiastolic == null || v.fetalHr == null),
    );
    expect(nullVisitFieldPatients.length).toBeGreaterThan(0);

    await expect(
      processAncWebhook(db, hospitalId, ancFixture, asSse(sseManager)),
    ).resolves.not.toThrow();
  });

  it('Thai characters in patient names are stored and retrieved without corruption', async () => {
    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    await processAncWebhook(db, hospitalId, ancFixture, asSse(sseManager));

    // All journeys were inserted — just verify count, not decrypted content
    const rows = await db.query<{ count: number }>(
      'SELECT COUNT(*) as count FROM maternal_journeys WHERE hospital_id = ?',
      [hospitalId],
    );
    // If Thai string caused corruption/error, rows would be 0
    expect(rows[0].count).toBe(ancFixture.patients.length);
  });

  it('labor patients with anc_count null do not cause CPD score errors', async () => {
    const laborFixture = loadFixture<WebhookPayload>('labor-patients.json');
    const now = new Date().toISOString();
    const laborHospitalId = uuidv4();
    await db.execute(
      `INSERT INTO hospitals (id, hcode, name, level, is_active, connection_status, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        laborHospitalId,
        // hcode is VARCHAR(5) — Postgres rejects a longer value even though
        // SQLite silently accepted it. Swap the last char instead of
        // appending a suffix so this stays distinct from the ANC-fixture
        // hospital seeded in beforeEach while fitting the column.
        laborFixture.hospitalCode.slice(0, 4) + 'L',
        'รพ.Labor Edge',
        'M1',
        true,
        'UNKNOWN',
        now,
        now,
      ],
    );
    await createApiKey(db, laborHospitalId, 'Labor Edge Key');

    await expect(
      processWebhookPayload(db, laborHospitalId, laborFixture, asSse(sseManager)),
    ).resolves.not.toThrow();
  });

  it('ANC visit dates span Aug 2024–Feb 2025 range (multi-month real data)', () => {
    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    const allDates: Date[] = [];
    for (const p of ancFixture.patients) {
      for (const v of p.visits ?? []) {
        allDates.push(new Date(v.date));
      }
    }
    const earliest = new Date(Math.min(...allDates.map((d) => d.getTime())));
    const latest = new Date(Math.max(...allDates.map((d) => d.getTime())));
    // Earliest visit: 2024-07-30, Latest: 2025-02-25
    expect(earliest.getFullYear()).toBe(2024);
    expect(latest.getFullYear()).toBe(2025);
    expect(latest.getTime()).toBeGreaterThan(earliest.getTime());
  });

  it('visit numbers within each patient are in chronological order', () => {
    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    for (const [i, p] of ancFixture.patients.entries()) {
      if (!p.visits || p.visits.length < 2) continue;
      for (let j = 1; j < p.visits.length; j++) {
        const prev = new Date(p.visits[j - 1].date);
        const curr = new Date(p.visits[j].date);
        expect(
          curr.getTime(),
          `patients[${i}] visits[${j}].date must be >= visits[${j - 1}].date`,
        ).toBeGreaterThanOrEqual(prev.getTime());
      }
    }
  });

  it('date formats in fixtures are consistent (YYYY-MM-DD or ISO 8601)', () => {
    const ancFixture = loadFixture<WebhookAncPayload>('anc-patients.json');
    const dateRe = /^\d{4}-\d{2}-\d{2}/; // YYYY-MM-DD prefix
    for (const p of ancFixture.patients) {
      expect(dateRe.test(p.birthday)).toBe(true);
      if (p.lmp) expect(dateRe.test(p.lmp)).toBe(true);
      if (p.edc) expect(dateRe.test(p.edc)).toBe(true);
      for (const v of p.visits ?? []) {
        expect(dateRe.test(v.date)).toBe(true);
      }
    }
    const laborFixture = loadFixture<WebhookPayload>('labor-patients.json');
    for (const p of laborFixture.patients) {
      // ISO 8601 with timezone — just ensure parseable
      expect(isNaN(new Date(p.admit_date).getTime())).toBe(false);
    }
  });
});
